version: '3.8'

services:
  terraform:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
